-- MySQL Script generated by MySQL Workbench
-- Thu May  4 10:00:11 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema permisos
-- -----------------------------------------------------
-- 
-- 

-- -----------------------------------------------------
-- Schema permisos
--
-- 
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `permisos` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `permisos` ;

-- -----------------------------------------------------
-- Table `permisos`.`recursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `permisos`.`recursos` (
  `idrecursos` INT NOT NULL AUTO_INCREMENT,
  `ruta` VARCHAR(250) NOT NULL,
  `usuarioAD` VARCHAR(45) NOT NULL,
  `usaurioNameCompleto` VARCHAR(150) NULL,
  `acceso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrecursos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
